PUT http://localhost:8888/api/accounts/edit/password
Content-Type: application/json

{
  "beforePassword": "1234",
  "newPassword": "1234",
  "checkNewPassword": "1234"
}

###

PUT http://localhost:8888/api/accounts/edit/profile
Content-Type: application/json

{
  "name": "min9",
  "website": "https://github.com/LeeSM0518",
  "introduction": "설명",
  "isPublicEmail": false
}

###