### 초기화 코드 요청(성공)
POST http://localhost:8888/api/accounts/password/email
Content-Type: application/json

{
  "email": "nalsm98@naver.com"
}

### 초기화 코드 요청(실패)
POST http://localhost:8888/api/accounts/password/email
Content-Type: application/json

{
  "email": "abc@naver.com"
}

### 비밀번호 초기화 요청(성공)
POST http://localhost:8888/api/accounts/password/reset
Content-Type: application/json

{
  "email": "nalsm98@naver.com",
  "code": "51765800"
}