POST http://localhost:8888/api/accounts/signup/email
Content-Type: application/json

{
  "email": "20171687@edu.hanbat.ac.kr"
}

###

POST http://localhost:8888/api/accounts/signup/code
Content-Type: application/json

{
  "email": "20171687@edu.hanbat.ac.kr",
  "code": "72578356"
}

###

POST http://localhost:8888/api/accounts/signup
Content-Type: application/json

{
  "email": " ",
  "name": "a a",
  "password": "1234",
  "interests": [
    "java"
  ]
}

###

POST http://localhost:8888/api/accounts/signup/email
Content-Type: application/json

{
  "email": "nalsm98@naver.com"
}

###

POST http://localhost:8888/api/accounts/signup/code
Content-Type: application/json

{
  "email": "nalsm98@naver.com",
  "code": "225835"
}

###

POST http://localhost:8888/api/accounts/signup
Content-Type: application/json

{
  "email": "nalsm98@naver.com",
  "name": "min2",
  "password": "1234",
  "interests": [
    "c"
  ]
}